apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metal3
resources:
- ../namespace
- ../rbac
- ../crds
- ../operator/redfish
configMapGenerator:
- envs:
  - redfish_bmo_configmap.env
  name: redfish-bmo-configmap
